### ISSUE TITLE
Add a `Window::get_monitor_id` method to get the monitor under the `Window`

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/winit#197] opened 2017-06-12 06:31 UTC
It seems that `NSWindow` has a method for this: https://developer.apple.com/documentation/appkit/nswindow. It also has a method for getting the "deepest" screen in the case that a window is split over multiple screens, though I'm not quite sure what this means.

I'm not yet sure if the other backends provide functionality for getting this info.

**Comment by mrec** [comment] 2017-06-12 19:27
Win32 has the [`MonitorFromWindow` function](https://msdn.microsoft.com/en-us/library/dd145064(v=vs.85).aspx) which does this. I don't know about X11/Wayland.

**Comment by mitchmindtree** [comment] 2017-06-18 12:51
@vberger is it possible to determine which monitor is under the window in the wayland backend? E.g. is it possible to determine the `WlOutput` that has the largest intersection with a `Window`'s area?

**Comment by vberger** [comment] 2017-06-18 20:38
Yes it is possible to track that.

Whenever the output that has the largest intesection with the window changes, the wayland compositor notifies the client with a appropriate event. It'd then be up to winit to track which is the current output displaying the client.

**Comment by mitchmindtree** [comment] 2017-06-19 02:05
@vberger I wonder if we could do something like this:

A window moves from monitor *A* to *B* when both of the following condition are met:

1. *enter* is called for *B* and
2. *leave* is called for *A*?

This might not be as nice as picking the monitor with the largest intersection, but better than nothing?

**Comment by vberger** [comment] 2017-06-19 05:53
Yes, but if a window stops mid-way, overlapping both A and B, we receive an "enter" event for B, but no "leave" event for B.

I think, from a conception point of view, the only reason wayland clients know about the outputs they are displayed on, is for DPI awareness (so they can draw their content according to the highest DPI output they are displayed on).

But overall, it's a clear will from the wayland conceptors that a wayland client does not know about its surroundings (where its window is displayed on the screen, whether or not it is overlapping with other windows, etc...). Mostly for security/privacy reasons I believe.

**Comment by mitchmindtree** [comment] 2017-06-22 11:05
Yeah I am also open to the idea of implementing a method that returns an iterator yielding each of the intersecting monitors, however I thought I'd start with a simple `monitor_id` method as:

1. It could be tricky to agree upon an order for the monitors (e.g. do we order by largest intersection? position? time of first intersection?)
2. The other OSes (macos, windows, x11) have the concept of a single monitor being the "main"  monitor upon which a window is situated.
3. I imagine it might require more work on some of the other OSes to find this info, though I could be wrong!

All that said, I like the idea of introducing a way of retrieving all intersecting monitors. Although perhaps we could instead implement a `get_position()` method for `MonitorId`, and then users can easily find intersecting monitors using a combination of `get_available_monitors`, `get_position` and `get_dimensions`?

**Comment by vberger** [comment] 2017-06-22 11:49
Something like `get_position()` would not be possible at all on wayland, by design. The client cannot know where it is located on a monitor, or how the monitors are located relative to each other.

Actually, the hypothesis that this have any sense at all can be wrong, see https://www.youtube.com/watch?v=_FjuPn7MXMs or https://github.com/evil0sheep/motorcar for example

**Comment by mitchmindtree** [comment] 2017-06-23 05:05
Ahh my mistake, thanks for clarifying @Ralith!

The main reason I originally started wanting this `monitor_id` API in particular was for the [redesign of glutin](https://github.com/tomaka/glutin/pull/897) that I'm working on - in particular, [this section](https://github.com/tomaka/glutin/pull/897/files#diff-e24e3ccc2abef223529e2f0fbdba35d3L137) of the X11 backend. It requires knowing the `screen_id` in order to be able to instantiate a GLX context. The GLX context seems to use it to query the extensions string which describes the list of available extensions. Originally, the `screen_id` was retrieved from the `winit::WindowBuilder`, however after the redesign there would no longer be access to the `winit::WindowBuilder`, only the pre-built `winit::Window`. Thus I thought it would be useful to add this `monitor_id` method. Perhaps there is a better way around that issue altogether?

**Comment by Ralith** [comment] 2017-06-23 06:16
I don't think there's any reasonable cross-platform interpretation of what a "screen" on a modern-day X server is. I expect `XDefaultScreen` will do the right thing in any typical desktop context, but in principle you do want to get it from the window. Isn't this what we have [the WindowExt method](https://docs.rs/winit/0.6.4/winit/os/unix/trait.WindowExt.html#tymethod.get_xlib_screen_id) for?

**Comment by mitchmindtree** [comment] 2017-06-23 07:23
Oh true! I totally missed these WindowExt methods, my apologies 🙇

**Comment by francesca64** [comment] 2018-05-06 18:12
This seems to be implemented on all platforms, so closing.

**Closed by francesca64** 2018-05-06 18:12 UTC
Labels: type: api
