### ISSUE TITLE
iOS checks isMainThread before UIApplication is started

### ISSUE THREAD

**Issue by seivan** [tomaka/winit#673] opened 2018-10-11 15:09 UTC
https://github.com/tomaka/winit/blob/808638fee3967d02023b02de2b90caaddb2d2f65/src/platform/ios/mod.rs#L212

Does this actually work? 

`isMainThread` will return false  if it's checked outside `UIApplication` and as far as I can see, the event loop is created before the `Window` and it's the `Window` that starts `UIApplication`

**Comment by francesca64** [comment] 2018-10-13 00:30
Why did you close this?

**Comment by seivan** [comment] 2018-10-13 00:32
I wasn’t sure how the jmp stuff works, since I assume it works I guess it’s because a UIApplicationMain is already setup somehow magically.

**Comment by francesca64** [comment] 2018-10-13 00:42
The app finishes launching before anything in the `setjmp` block is executed, but that happens in `Window::new`, not `EventsLoop::new`. The `isMainThread` check will thus always happen *before* `UIApplicationMain`, at least as far as I can tell.

**Comment by francesca64** [comment] 2018-10-14 23:00
It's quite possible that it's never really been tested, and might've just been added at the same time as the equivalent check on macOS.

**Comment by mtak-** [comment] 2018-11-14 22:17
I will look into this as part of the EventLoop 2.0 rewrite.

**Comment by mtak-** [comment] 2018-11-14 23:21
It has the expected behavior in my simple tests (returns false on a pthread other than the main thread, and true on the main thread even before `UIApplicatinMain`), and [this SO](https://stackoverflow.com/a/14701112/3973558) post backs that up (SO is never wrong right?).

On the other hand, I couldn't find any documentation explicitly saying that this was OK.

**Comment by francesca64** [comment] 2018-11-17 06:40
I haven't found any documentation that suggests this wouldn't be okay, and since it works, I think we're safe!

**Closed by francesca64** 2018-11-17 06:40 UTC
Labels: platform: iOS
