### ISSUE TITLE
Monitors are not detected properly

### ISSUE THREAD

**Issue by tomaka** [tomaka/winit#75] opened 2016-11-03 08:12 UTC
Original: https://github.com/tomaka/glutin/issues/787

**Comment by mitchmindtree** [comment] 2017-06-18 17:24
I'm also running into this issue when running x11 with my dual monitor setup. Will hopefully get a chance to look into this within the next few days.

**Comment by jwilm** [comment] 2017-10-09 01:25
Looks like a duplicate of #64

**Closed** 2018-05-06 17:17 UTC
Labels: platform: X11
